AllCops:
  TargetRubyVersion: 2.5
  Include:
    - lib/**/*.rb

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - bin/**

Style/Semicolon:
  Exclude:
    - test/**/*
